# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocr_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_image_path = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_image_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_image_path.setSizePolicy(sizePolicy)
        self.lineEdit_image_path.setObjectName("lineEdit_image_path")
        self.horizontalLayout.addWidget(self.lineEdit_image_path)
        self.pushButton_choose_picture = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_choose_picture.sizePolicy().hasHeightForWidth())
        self.pushButton_choose_picture.setSizePolicy(sizePolicy)
        self.pushButton_choose_picture.setObjectName("pushButton_choose_picture")
        self.horizontalLayout.addWidget(self.pushButton_choose_picture)
        self.pushButton_start_recognition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_recognition.sizePolicy().hasHeightForWidth())
        self.pushButton_start_recognition.setSizePolicy(sizePolicy)
        self.pushButton_start_recognition.setObjectName("pushButton_start_recognition")
        self.horizontalLayout.addWidget(self.pushButton_start_recognition)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_screenshort_image = QtWidgets.QLabel(self.centralwidget)
        self.label_screenshort_image.setText("")
        self.label_screenshort_image.setObjectName("label_screenshort_image")
        self.horizontalLayout_2.addWidget(self.label_screenshort_image, 0, QtCore.Qt.AlignLeft)
        self.pushButton_screenshort_paste = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_screenshort_paste.sizePolicy().hasHeightForWidth())
        self.pushButton_screenshort_paste.setSizePolicy(sizePolicy)
        self.pushButton_screenshort_paste.setObjectName("pushButton_screenshort_paste")
        self.horizontalLayout_2.addWidget(self.pushButton_screenshort_paste)
        self.pushButton_screenshort_recognition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_screenshort_recognition.sizePolicy().hasHeightForWidth())
        self.pushButton_screenshort_recognition.setSizePolicy(sizePolicy)
        self.pushButton_screenshort_recognition.setObjectName("pushButton_screenshort_recognition")
        self.horizontalLayout_2.addWidget(self.pushButton_screenshort_recognition)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.textEdit_result.sizePolicy().hasHeightForWidth())
        self.textEdit_result.setSizePolicy(sizePolicy)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout.addWidget(self.textEdit_result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 544, 22))
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_choose_picture.setText(_translate("MainWindow", "选择图片"))
        self.pushButton_start_recognition.setText(_translate("MainWindow", "图片识别"))
        self.pushButton_screenshort_paste.setText(_translate("MainWindow", "粘贴截图"))
        self.pushButton_screenshort_recognition.setText(_translate("MainWindow", "截图识别"))
        self.label_title.setText(_translate("MainWindow", "识别结果"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionView.setToolTip(_translate("MainWindow", "aa"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFile.setToolTip(_translate("MainWindow", "menu"))

